version: '3.4'

services:
  demo2-mongodb:
    image: mongo:latest
    container_name: demo2-mongodb
    ports:
      - 27017:27017
  demo2-api:
    image: demo2api:latest
    container_name: demo2-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=demo2-mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=happeo
    depends_on:
      - demo2-mongodb
    links:
      - demo2-mongodb
