package com.happeo.userprovisioning.demo2api.model.users;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "user")
public class User {

    @Id
    private Integer id;                     // - Happeo User’s internal autogenerated id
    private Integer organisationId = 1;     // - Organisation ID of the user
    private Integer externalId;             // ID of the user in the external system (null for internal user of Happeo)

    private String email;
    private String firstName;
    private String lastName;
    private String password;
    private Boolean isActive;

    // public User() {}

    // public User(Long id, int externalId, String email, String firstName, String lastName, Boolean isActive) {
    //     this.id = id;
    //     this.email = email;
    //     this.firstName = firstName;
    //     this.lastName = lastName;
    //     this.isActive = isActive;
    // }

    @Override
    public String toString() {
      return String.format(
          "User[id=%s, firstName='%s', lastName='%s', isAcive='%s']",
          id, firstName, lastName, isActive);
    }
}
